# Generated by Django 5.2.12 on 2026-09-30 18:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentevent',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payment_amount_non_negative',
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_code',
            field=models.CharField(blank=True, default='', help_text="Provider's machine-readable failure code, for reporting.", max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Client-supplied key so a retried checkout request returns the existing payment instead of a new one.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who received the money. Required for manual / cash payments.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='User who caused the event; null for system / webhooks.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerwebhooklog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='providerwebhooklog',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerwebhooklog',
            name='provider_event_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='providerwebhooklog',
            name='raw_body',
            field=models.TextField(blank=True, default='', help_text='Exact bytes received (decoded). Signatures are computed over this, and it survives unparseable payloads.'),
        ),
        migrations.AddField(
            model_name='refund',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='refund',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='refund',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of SUCCEEDED refunds. Only change via Refund.mark_succeeded().', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Whitelisted, non-secret extras only. Raw provider responses belong in PaymentEvent.payload or ProviderWebhookLog.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('chapa', 'Chapa'), ('telebirr', 'Telebirr'), ('cbe_birr', 'CBE Birr'), ('manual', 'Manual / Cash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_reference',
            field=models.CharField(blank=True, default='', help_text="The provider's own transaction id / tx_ref.", max_length=128),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='providerwebhooklog',
            name='provider',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='providerwebhooklog',
            index=models.Index(fields=['processed', 'received_at'], name='payments_pr_process_2bd388_idx'),
        ),
        migrations.AddIndex(
            model_name='providerwebhooklog',
            index=models.Index(fields=['provider', 'provider_event_id'], name='payments_pr_provide_61a989_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status'], name='payments_re_payment_4444a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_refunded__gte', 0), ('amount_refunded__lte', models.F('amount'))), name='payment_refunded_within_amount'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('provider', 'provider_reference'), name='uniq_payment_provider_reference'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('payer', 'idempotency_key'), name='uniq_payment_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content_type__isnull', True), ('object_id__isnull', True)), models.Q(('content_type__isnull', False), ('object_id__isnull', False)), _connector='OR'), name='payment_payable_both_or_neither'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('provider', 'manual'), _negated=True), ('recorded_by__isnull', False), _connector='OR'), name='payment_manual_requires_recorded_by'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('payment', 'provider_reference'), name='uniq_refund_provider_reference'),
        ),
    ]
