# Generated by Django 5.2.12 on 2026-10-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentevent_options_alter_refund_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Test payable (testing only)',
            },
        ),
    ]
