"""
Django settings for Backend project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# DJANGO_ENV defaults to "dev". Set it to "prod" in production.
_ENV = os.environ.get("DJANGO_ENV", "dev")
_env_file = BASE_DIR / f".env.{_ENV}"
if _env_file.exists():
    load_dotenv(_env_file, override=False)

load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "ALLOWED_HOSTS", ""
    ).split(",")
    if host.strip()
]

render_hostname = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if render_hostname and render_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_hostname)

# ======================================================
# APPLICATIONS
# ======================================================

INSTALLED_APPS = [
    "daphne",

    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "corsheaders",
    "django_filters",
    "rest_framework",
    "rest_framework.authtoken",
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'channels',

    # Local apps
    "accounts",
    "services",
    "families",
    "executive",
    "roles",
    "health_data",
    "appointments",
    "consultations",
    "doctors",
    "notifications",
    "patients",
    "chat",
    "payments",
]

# ======================================================
# AUTH
# ======================================================

AUTH_USER_MODEL = "accounts.User"
LOGIN_URL = "/login/"
LOGOUT_REDIRECT_URL = "/"

# ======================================================
# MIDDLEWARE (ORDER MATTERS)
# ======================================================

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # must be first
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ======================================================
# CORS & CSRF (CRITICAL FOR REACT)
# ======================================================
CORS_ALLOW_CREDENTIALS = True


CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

#CSRF_COOKIE_HTTPONLY = True  # React needs to read it
#CSRF_COOKIE_SAMESITE = "Lax"
#SESSION_COOKIE_SAMESITE = "Lax"

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# ======================================================
# URLS / TEMPLATES
# ======================================================

ROOT_URLCONF = 'Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Backend.wsgi.application'
ASGI_APPLICATION = 'Backend.asgi.application'

# ======================================================
# REDIS / CACHE / CHANNELS
# ======================================================

REDIS_URL = os.environ.get("REDIS_URL")

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    # Development fallback only
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }

    print("WARNING: REDIS_URL not configured. Using in-memory cache/channel layer.")

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ======================================================
# DATABASE
# ======================================================
DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL"),
        conn_max_age=600,
    )
}

# ======================================================
# PASSWORD VALIDATION
# ======================================================

AUTHENTICATION_BACKENDS = [   
    "accounts.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",]

# ======================================================
# DJANGO REST FRAMEWORK (SESSION AUTH DEFAULT)
# ======================================================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "login": "10/minute",  # 
        "registration": "5/hour",  # 
        "patient_claim": "5/hour",

        "family_invitation_create": "20/hour",
        "family_patient_create": "20/hour",

        "payment_poll": "60/minute",
        "payment_initiate": "10/minute",

        "invitation_lookup": "30/min",
        "invitation_contact": "5/min",
        "invitation_otp": "5/min",
        "invitation_registration": "10/min",
        "family_invitation_create": "20/hour",
        "family_member_write": "60/hour",
        "family_overview": "120/min",
    },
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth."
            "password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth."
            "password_validation.MinimumLengthValidator"
        ),
        "OPTIONS": {
            "min_length": 12,
        },
    },
    {
        "NAME": (
            "django.contrib.auth."
            "password_validation.CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth."
            "password_validation.NumericPasswordValidator"
        ),
    },
]

# ======================================================
# JWT READY (UNCOMMENT WHEN NEEDED)
# ======================================================

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.MD5PasswordHasher",
]

# ======================================================
# INTERNATIONALIZATION
# ====================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ======================================================
# STATIC & MEDIA FILES
# ======================================================

STATIC_URL = "/static/"

# ✅ MUST be a single path
STATIC_ROOT = BASE_DIR / "staticfiles"

# ✅ MUST be a flat list of paths
STATICFILES_DIRS = []

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Telebirr ────────────────────────────────────────────
TELEBIRR_MODE = os.environ.get("TELEBIRR_MODE", "mock")
TELEBIRR_MERCHANT_APP_ID = os.environ.get("TELEBIRR_MERCHANT_APP_ID", "dev-merchant-app-id")
TELEBIRR_APP_SECRET = os.environ.get("TELEBIRR_APP_SECRET", "dev-app-secret")
TELEBIRR_SHORT_CODE = os.environ.get("TELEBIRR_SHORT_CODE", "123456")
TELEBIRR_BASE_URL = os.environ.get(
    "TELEBIRR_BASE_URL", "http://localhost:9000/mock-telebirr",
)
TELEBIRR_NOTIFY_URL = os.environ.get(
    "TELEBIRR_NOTIFY_URL", "http://localhost:8000/webhooks/telebirr/notify/",
)
TELEBIRR_RETURN_URL = os.environ.get(
    "TELEBIRR_RETURN_URL", "http://localhost:8000/webhooks/telebirr/return/",
)
TELEBIRR_RETURN_REDIRECT_URL = os.environ.get(
    "TELEBIRR_RETURN_REDIRECT_URL", "/payments/status/",
)

def _read_pem(env_var: str) -> str:
    """Load a PEM from a path in an env var, or inline content."""
    inline = os.environ.get(env_var, "")
    if inline.strip().startswith("-----BEGIN"):
        return inline.replace("\\n", "\n")

    raw_path = os.environ.get(f"{env_var}_PATH", "")
    if not raw_path:
        return ""
    p = Path(raw_path)
    if not p.is_absolute():
        p = BASE_DIR / p
    return p.read_text() if p.exists() else ""

TELEBIRR_PUBLIC_KEY = _read_pem("TELEBIRR_PUBLIC_KEY")
TELEBIRR_PRIVATE_KEY = _read_pem("TELEBIRR_PRIVATE_KEY")

# Fail loud in production if anything is missing.
if _ENV == "prod":
    _required = [
        "TELEBIRR_MERCHANT_APP_ID", "TELEBIRR_APP_SECRET",
        "TELEBIRR_SHORT_CODE", "TELEBIRR_BASE_URL",
        "TELEBIRR_NOTIFY_URL", "TELEBIRR_RETURN_URL",
    ]
    _missing = [n for n in _required if not globals().get(n)]
    if _missing:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            f"Missing in production: {', '.join(_missing)}"
        )
    if not TELEBIRR_PUBLIC_KEY or not TELEBIRR_PRIVATE_KEY:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            "TELEBIRR_PUBLIC_KEY / TELEBIRR_PRIVATE_KEY could not be loaded."
        )

# ====================================================== 
# END OF SETTINGS
# ======================================================
