# Generated by Django 5.2.12 on 2026-09-25 11:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Feature Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('code', models.SlugField(help_text="Stable identifier used in APIs/URLs, e.g. 'annual-checkup'.", unique=True, validators=[django.core.validators.RegexValidator(message="Code must be lowercase alphanumeric, using hyphens to separate words (e.g. 'annual-checkup').", regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')], verbose_name='Service Code')),
                ('name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('service_for', models.CharField(choices=[('individual', 'Individual'), ('family', 'Family'), ('executive', 'Executive'), ('organization', 'Organization')], db_index=True, max_length=20, verbose_name='Service For')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_services', to='services.feature')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_features', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Feature',
                'verbose_name_plural': 'Service Features',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='services', through='services.ServiceFeature', to='services.feature'),
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('onboarded', models.BooleanField(default=False, verbose_name='Onboarding complete')),
                ('onboarded_at', models.DateTimeField(blank=True, null=True, verbose_name='Onboarded at')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined at')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_services', to='services.service', verbose_name='Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_services', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Service',
                'verbose_name_plural': 'User Services',
            },
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['is_active', 'is_deleted'], name='services_fe_is_acti_0ac5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefeature',
            index=models.Index(fields=['service', 'display_order'], name='services_se_service_916e28_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicefeature',
            constraint=models.UniqueConstraint(fields=('service', 'feature'), name='unique_service_feature'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_for', 'is_active'], name='services_se_service_13f94b_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'is_deleted'], name='services_se_is_acti_c8fa36_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('name', 'service_for'), name='unique_service_name_per_audience'),
        ),
        migrations.AddIndex(
            model_name='userservice',
            index=models.Index(fields=['user', 'service'], name='services_us_user_id_cf09cd_idx'),
        ),
        migrations.AddIndex(
            model_name='userservice',
            index=models.Index(fields=['user', 'onboarded'], name='services_us_user_id_7a8a00_idx'),
        ),
        migrations.AddConstraint(
            model_name='userservice',
            constraint=models.UniqueConstraint(fields=('user', 'service'), name='unique_user_service'),
        ),
    ]
