# Generated by Django 5.2.12 on 2026-09-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultationprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationprofile',
            name='onboarded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
