# Generated by Django 5.2.12 on 2026-10-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_options_and_more'),
        ('consultations', '0003_alter_consultationprofile_onboarded_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='consultationprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status', 'created_at'], name='consultatio_status_4e67fd_idx'),
        ),
    ]
