# Generated by Django 5.2.12 on 2026-10-03 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_type', models.CharField(choices=[('observer', 'Read-only observer')], default='observer', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('can_view_readings', models.BooleanField(default=True)),
                ('can_view_care_plan', models.BooleanField(default=True)),
                ('can_view_visits', models.BooleanField(default=True)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_view_prescriptions', models.BooleanField(default=True)),
                ('can_view_lab_results', models.BooleanField(default=True)),
                ('can_view_history', models.BooleanField(default=True)),
                ('can_view_attention', models.BooleanField(default=True)),
                ('can_view_care_team', models.BooleanField(default=True)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('otp_hash', models.CharField(blank=True, default='', max_length=64)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveIntegerField(default=0)),
                ('otp_locked_at', models.DateTimeField(blank=True, null=True)),
                ('contact_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_family_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family_invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_families', to=settings.AUTH_USER_MODEL)),
                ('user_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family_profiles', to='services.userservice')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('name'), nulls_last=True)],
            },
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('observer', 'Observer')], max_length=20)),
                ('can_view_readings', models.BooleanField(default=True)),
                ('can_view_care_plan', models.BooleanField(default=True)),
                ('can_view_visits', models.BooleanField(default=True)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_view_prescriptions', models.BooleanField(default=True)),
                ('can_view_lab_results', models.BooleanField(default=True)),
                ('can_view_history', models.BooleanField(default=True)),
                ('can_view_attention', models.BooleanField(default=True)),
                ('can_view_care_team', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_memberships_invited', to=settings.AUTH_USER_MODEL)),
                ('invited_via', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_memberships', to='families.familyinvitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='families.familyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('relationship', models.CharField(choices=[('self', 'Self'), ('mother', 'Mother'), ('father', 'Father'), ('parent', 'Parent'), ('spouse', 'Spouse'), ('child', 'Child'), ('sibling', 'Sibling'), ('relative', 'Relative'), ('other', 'Other')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary member of the family (typically the account owner).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='families.familyprofile')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='families.familyprofile'),
        ),
        migrations.CreateModel(
            name='FamilyCareTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('nurse', 'Assigned Nurse'), ('coordinator', 'Care Coordinator'), ('physician', 'Physician')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('available_now', models.BooleanField(default=True)),
                ('on_visit', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_care_assignments', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_team', to='families.familyprofile')),
            ],
            options={
                'ordering': ['-is_primary', 'role', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('family_created', 'Family Created'), ('member_created', 'Family Member Created'), ('observer_invited', 'Observer Invited'), ('invitation_otp_requested', 'Invitation OTP Requested'), ('invitation_contact_verified', 'Invitation Contact Verified'), ('observer_accepted', 'Observer Accepted (existing user)'), ('observer_registered', 'Observer Registered (new user)'), ('invitation_cancelled', 'Invitation Cancelled'), ('invitation_expired', 'Invitation Expired'), ('otp_locked', 'OTP Verification Locked'), ('membership_revoked', 'Family Membership Revoked'), ('membership_perms_changed', 'Membership Permissions Changed')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='families.familyinvitation')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='families.familyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyAttentionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('tone', models.CharField(choices=[('good', 'Good'), ('info', 'Info'), ('flag', 'Flag')], default='info', max_length=10)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attention_flags', to='families.familymember')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_flags', to='families.familyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bp', 'Blood Pressure'), ('medication', 'Medication'), ('blood_sample', 'Blood Sample'), ('ankle_swelling', 'Ankle Swelling'), ('heart_rate', 'Heart Rate'), ('spo2', 'Oxygen Saturation'), ('temperature', 'Temperature'), ('weight', 'Weight'), ('blood_glucose', 'Blood Glucose'), ('other', 'Other')], max_length=32)),
                ('value', models.CharField(max_length=64)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('tone', models.CharField(choices=[('good', 'Good'), ('info', 'Info'), ('flag', 'Flag')], default='good', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='families.familymember')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_readings_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weekly', 'Weekly summary'), ('monthly', 'Monthly review'), ('post_visit', 'Post-visit recap'), ('ad_hoc', 'Ad-hoc report')], default='weekly', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('tone', models.CharField(choices=[('good', 'Good'), ('info', 'Info'), ('flag', 'Flag')], default='info', max_length=10)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='families.familymember')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyReportRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='families.familyreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_report_reads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('destination', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='families.familyinvitation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyLabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('collected_at', models.DateField()),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('review', 'Review'), ('abnormal', 'Abnormal')], default='normal', max_length=20)),
                ('tone', models.CharField(choices=[('good', 'Good'), ('info', 'Info'), ('flag', 'Flag')], default='good', max_length=10)),
                ('file_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='families.familymember')),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['member', '-collected_at'], name='flr_member_coll_idx'), models.Index(fields=['member', 'status'], name='flr_member_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='FamilyHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('tone', models.CharField(choices=[('good', 'Good'), ('info', 'Info'), ('flag', 'Flag')], default='good', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='families.familymember')),
            ],
            options={
                'verbose_name_plural': 'family history entries',
                'ordering': [models.OrderBy(models.F('year'), descending=True, nulls_last=True), '-created_at'],
                'indexes': [models.Index(fields=['member', '-year'], name='fhe_member_year_idx')],
            },
        ),
        migrations.CreateModel(
            name='CareVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_name', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_conducted', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='families.familymember')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('started_at'), descending=True, nulls_last=True), models.OrderBy(models.F('scheduled_at'), descending=True, nulls_last=True), '-created_at'],
                'indexes': [models.Index(fields=['member', 'state'], name='cv_member_state_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('scheduled_time', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('done', 'Done'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='upcoming', max_length=10)),
                ('done', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_plan_items_completed', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plan_items', to='families.familymember')),
            ],
            options={
                'ordering': ['order', 'scheduled_time'],
                'indexes': [models.Index(fields=['member', 'status'], name='cpi_member_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='FamilyPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=100)),
                ('prescribed_by', models.CharField(max_length=200)),
                ('refill_note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('refill_soon', 'Refill soon'), ('expired', 'Expired'), ('stopped', 'Stopped')], default='active', max_length=20)),
                ('tone', models.CharField(choices=[('good', 'Good'), ('info', 'Info'), ('flag', 'Flag')], default='good', max_length=10)),
                ('started_at', models.DateField(default=django.utils.timezone.localdate)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='families.familymember')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member', 'status'], name='fpres_member_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='familyprofile',
            index=models.Index(fields=['created_by'], name='fp_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='familyprofile',
            index=models.Index(fields=['user_service'], name='fp_user_service_idx'),
        ),
        migrations.AddIndex(
            model_name='familymembership',
            index=models.Index(fields=['user', 'revoked_at'], name='fmem_user_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='familymembership',
            index=models.Index(fields=['family', 'role'], name='fmem_family_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='familymembership',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('family', 'user'), name='unique_active_family_membership'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['family', 'relationship'], name='fm_family_rel_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['family', 'full_name'], name='fm_family_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('family',), name='unique_primary_family_member'),
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['family', 'status'], name='fi_family_status_idx'),
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['status', 'expires_at'], name='fi_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['email', 'status'], name='fi_email_status_idx'),
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['phone_number', 'status'], name='fi_phone_status_idx'),
        ),
        migrations.AddIndex(
            model_name='familycareteammember',
            index=models.Index(fields=['family', 'role'], name='fctm_family_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='familycareteammember',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('family', 'staff', 'role'), name='unique_active_care_team_assignment'),
        ),
        migrations.AddIndex(
            model_name='familyauditlog',
            index=models.Index(fields=['family', '-created_at'], name='fa_family_created_idx'),
        ),
        migrations.AddIndex(
            model_name='familyauditlog',
            index=models.Index(fields=['actor', '-created_at'], name='fa_actor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='familyauditlog',
            index=models.Index(fields=['action', '-created_at'], name='fa_action_created_idx'),
        ),
        migrations.AddIndex(
            model_name='familyauditlog',
            index=models.Index(fields=['invitation', '-created_at'], name='fa_inv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='familyattentionflag',
            index=models.Index(fields=['family', 'resolved'], name='faf_family_res_idx'),
        ),
        migrations.AddIndex(
            model_name='familyattentionflag',
            index=models.Index(fields=['member', 'resolved'], name='faf_member_res_idx'),
        ),
        migrations.AddIndex(
            model_name='familyreading',
            index=models.Index(fields=['member', 'kind', '-recorded_at'], name='fr_member_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='familyreading',
            index=models.Index(fields=['member', '-recorded_at'], name='fr_member_rec_idx'),
        ),
        migrations.AddIndex(
            model_name='familyreport',
            index=models.Index(fields=['member', '-published_at'], name='frep_member_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='familyreportread',
            index=models.Index(fields=['user', '-read_at'], name='frr_user_read_idx'),
        ),
        migrations.AddConstraint(
            model_name='familyreportread',
            constraint=models.UniqueConstraint(fields=('report', 'user'), name='unique_report_read_per_user'),
        ),
        migrations.AddIndex(
            model_name='invitationdelivery',
            index=models.Index(fields=['invitation', 'status'], name='id_inv_status_idx'),
        ),
    ]
