# Generated by Django 5.2.12 on 2026-10-03 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familyauditlog',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='families.familymember'),
        ),
        migrations.AddIndex(
            model_name='familyauditlog',
            index=models.Index(fields=['member', '-created_at'], name='fa_member_created_idx'),
        ),
    ]
