# Generated by Django 5.2.12 on 2026-09-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('scheduled_time', models.CharField(blank=True, max_length=16)),
                ('done', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='CareVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_name', models.CharField(max_length=150)),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('inProgress', 'In Progress'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyAttentionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(blank=True, max_length=255)),
                ('tone', models.CharField(choices=[('info', 'Info'), ('flag', 'Flag')], default='info', max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyCareTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('nurse', 'Assigned Nurse'), ('coordinator', 'Care Coordinator'), ('physician', 'Physician')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('available_now', models.BooleanField(default=True)),
                ('on_visit', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['role', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bp', 'Blood Pressure'), ('medication', 'Medication'), ('bloodSample', 'Blood Sample'), ('ankleSwelling', 'Ankle Swelling'), ('other', 'Other')], max_length=20)),
                ('value', models.CharField(max_length=64)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('tone', models.CharField(choices=[('good', 'Good'), ('info', 'Info'), ('flag', 'Flag')], default='good', max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['full_name']},
        ),
        migrations.RemoveConstraint(
            model_name='familymember',
            name='unique_family_member',
        ),
        migrations.RemoveConstraint(
            model_name='familymember',
            name='unique_family_owner',
        ),
        migrations.RemoveIndex(
            model_name='familymember',
            name='families_fa_family__e485f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='familymember',
            name='families_fa_user_id_3190e0_idx',
        ),
        migrations.RenameField(
            model_name='familymember',
            old_name='family',
            new_name='family_profile',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='can_manage_appointments',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='can_manage_family_members',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='can_manage_family_patients',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='can_manage_medications',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='can_view_patient_records',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='role',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='user',
        ),
        migrations.AddField(
            model_name='familymember',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='familymember',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='familymember',
            name='full_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familymember',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('parent', 'Parent'), ('spouse', 'Spouse'), ('child', 'Child'), ('other', 'Other')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familyinvitation',
            name='role',
            field=models.CharField(blank=True, choices=[('mother', 'Mother'), ('father', 'Father'), ('parent', 'Parent'), ('spouse', 'Spouse'), ('child', 'Child'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='careplanitem',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plan_items', to='families.familymember'),
        ),
        migrations.AddField(
            model_name='carevisit',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='families.familymember'),
        ),
        migrations.AddField(
            model_name='familyattentionflag',
            name='family_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_flags', to='families.familyprofile'),
        ),
        migrations.AddField(
            model_name='familycareteammember',
            name='family_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_team', to='families.familyprofile'),
        ),
        migrations.AddField(
            model_name='familyreading',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='families.familymember'),
        ),
    ]
