# Generated by Django 5.2.12 on 2026-09-26 07:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_careplanitem_carevisit_familyattentionflag_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('swelling', 'Swelling'), ('pain', 'Pain'), ('mood', 'Mood'), ('appetite', 'Appetite'), ('skin', 'Skin condition'), ('other', 'Other')], max_length=16)),
                ('label', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('good', 'Good'), ('info', 'Info'), ('flag', 'Needs attention')], default='info', max_length=8)),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('done', 'Done'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='upcoming', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_tasks_completed', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_tasks', to='patients.patient')),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['patient', 'scheduled_at'], name='families_ca_patient_2f545d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CareTeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('nurse', 'Assigned nurse'), ('coordinator', 'Care coordinator'), ('doctor', 'Doctor')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_team', to='patients.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'role'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('patient', 'staff', 'role'), name='unique_active_care_assignment')],
            },
        ),
        migrations.CreateModel(
            name='PatientAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'resolved_at'], name='families_pa_patient_52d571_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_conducted', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='families_se_patient_259fe8_idx')],
            },
        ),
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('blood_pressure', 'Blood pressure'), ('heart_rate', 'Heart rate'), ('spo2', 'Oxygen saturation'), ('temperature', 'Temperature'), ('weight', 'Weight'), ('blood_glucose', 'Blood glucose')], max_length=32)),
                ('value', models.CharField(max_length=64)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('good', 'Good'), ('info', 'Info'), ('flag', 'Needs attention')], default='good', max_length=8)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_readings', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_readings_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'kind', '-recorded_at'], name='families_vi_patient_688215_idx')],
            },
        ),
    ]
