# Generated by Django 5.2.12 on 2026-09-27 13:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_patientobservation_caretask_careteamassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('tone', models.CharField(choices=[('good', 'Good'), ('warn', 'Warn'), ('bad', 'Bad')], default='good', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='families.familymember')),
            ],
            options={
                'verbose_name_plural': 'family history entries',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyLabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('collected_at', models.DateField()),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('review', 'Review'), ('abnormal', 'Abnormal')], default='normal', max_length=20)),
                ('tone', models.CharField(choices=[('good', 'Good'), ('warn', 'Warn'), ('bad', 'Bad')], default='good', max_length=10)),
                ('file_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='families.familymember')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=100)),
                ('prescribed_by', models.CharField(max_length=200)),
                ('refill_note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('refill_soon', 'Refill soon'), ('expired', 'Expired'), ('stopped', 'Stopped')], default='active', max_length=20)),
                ('tone', models.CharField(choices=[('good', 'Good'), ('warn', 'Warn'), ('bad', 'Bad')], default='good', max_length=10)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='families.familymember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weekly', 'Weekly summary'), ('monthly', 'Monthly review'), ('post_visit', 'Post-visit recap'), ('ad_hoc', 'Ad-hoc report')], default='weekly', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('good', 'Good'), ('info', 'Info'), ('flag', 'Flag')], default='info', max_length=10)),
                ('is_new', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='families.familymember')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
