# Generated by Django 5.2.12 on 2026-09-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_doctor_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('doctor_visit', 'Doctor Visit'), ('home_visit', 'Home Visit'), ('nurse_check', 'Nurse Check'), ('lab_sample', 'Lab Sample')], db_index=True, default='doctor_visit', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='provider_name',
            field=models.CharField(blank=True, default='', help_text='Display name for non-doctor visits (nurse, lab tech, etc.).', max_length=150),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_minutes',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='How many minutes before the appointment to notify the patient.', null=True),
        ),
    ]
