# Generated by Django 5.2.12 on 2026-10-02 13:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_appointment_type_and_more'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'appointment_time']},
        ),
        migrations.AlterModelOptions(
            name='appointmentcheckin',
            options={'verbose_name': 'Appointment Check-In', 'verbose_name_plural': 'Appointment Check-Ins'},
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_doctor_date_time_idx',
            old_name='appointment_doctor__221180_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_patient_date_idx',
            old_name='appointment_patient_8037cd_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_status_date_idx',
            old_name='appointment_status_7c15d1_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Required for doctor visits; optional for nurse/lab visits.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Duration of the appointment in minutes.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason_for_visit',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appointmentcheckin',
            name='checked_in_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_type', 'appointment_date'], name='appt_type_date_idx'),
        ),
    ]
