# Generated by Django 5.2.12 on 2026-10-03 11:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('monitoring', models.JSONField(blank=True, default=list)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('twice', 'Twice Weekly'), ('managed', 'Managed')], default='managed', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_executive_profiles', to=settings.AUTH_USER_MODEL)),
                ('user_service', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='executive_profile', to='services.userservice')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('eta_minutes', models.PositiveSmallIntegerField(default=15)),
                ('activated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_events', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='CareTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('manager', 'Health Manager'), ('physician', 'Physician'), ('nurse', 'Nurse')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('available', models.BooleanField(default=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_team', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['role', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('flag', 'Flag')], default='info', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthProgrammeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('on', 'On'), ('soon', 'Soon'), ('booked', 'Booked'), ('track', 'On Track'), ('scheduled', 'Scheduled')], default='scheduled', max_length=20)),
                ('icon_key', models.CharField(blank=True, max_length=32)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('next_due', models.DateTimeField(blank=True, null=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_items', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HealthScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=64)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('tone', models.CharField(choices=[('normal', 'Normal'), ('elevated', 'Elevated'), ('high', 'High'), ('low', 'Low'), ('watch', 'Watch')], default='normal', max_length=20)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('purpose', models.CharField(blank=True, max_length=150)),
                ('dosage', models.CharField(blank=True, max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('reminder', 'Reminder')], default='reminder', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_alerts', to='executive.executiveprofile')),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='executive.medication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('taken', 'Taken'), ('due', 'Due'), ('upcoming', 'Upcoming'), ('missed', 'Missed')], default='upcoming', max_length=20)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='executive.medication')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('bp', 'Blood Pressure'), ('heartRate', 'Heart Rate'), ('oxygen', 'Oxygen'), ('weight', 'Weight'), ('glucose', 'Glucose'), ('general', 'General')], max_length=20)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('value_secondary', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. diastolic when metric=bp', max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('display_value', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('elevated', 'Elevated'), ('high', 'High'), ('low', 'Low'), ('watch', 'Watch')], default='normal', max_length=20)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='UpcomingCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('provided_by', models.CharField(blank=True, max_length=150)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_care', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('week', 'Week'), ('month', 'Month')], default='week', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('label', models.CharField(max_length=80)),
                ('range_label', models.CharField(max_length=80)),
                ('physician_name', models.CharField(blank=True, max_length=150)),
                ('nurse_name', models.CharField(blank=True, max_length=150)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('status_title', models.CharField(blank=True, max_length=120)),
                ('status_summary', models.TextField(blank=True)),
                ('vitals', models.JSONField(blank=True, default=list)),
                ('trends', models.JSONField(blank=True, default=list)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('next_steps', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyTimelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('current', 'Current'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('happened_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='executive.emergencyevent')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('event', 'order'), name='emergency_step_unique_order_per_event')],
            },
        ),
        migrations.AddIndex(
            model_name='executiveprofile',
            index=models.Index(fields=['deleted_at'], name='executive_e_deleted_18428f_idx'),
        ),
        migrations.AddConstraint(
            model_name='executiveprofile',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_at__isnull', True), ('deleted_at__isnull', False), _connector='OR'), name='exec_profile_deleted_flag'),
        ),
        migrations.AddIndex(
            model_name='emergencyevent',
            index=models.Index(fields=['executive_profile', 'status'], name='executive_e_executi_52bde6_idx'),
        ),
        migrations.AddConstraint(
            model_name='emergencyevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', False), ('status', 'resolved')), models.Q(('status', 'resolved'), _negated=True), _connector='OR'), name='emergency_resolved_requires_timestamp'),
        ),
        migrations.AddIndex(
            model_name='careteammember',
            index=models.Index(fields=['executive_profile', 'role'], name='executive_c_executi_1399db_idx'),
        ),
        migrations.AddIndex(
            model_name='healthalert',
            index=models.Index(fields=['executive_profile', 'resolved'], name='executive_h_executi_5c1ece_idx'),
        ),
        migrations.AddConstraint(
            model_name='healthalert',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved', False), ('resolved_at__isnull', True)), models.Q(('resolved', True), ('resolved_at__isnull', False)), _connector='OR'), name='health_alert_resolved_consistency'),
        ),
        migrations.AddIndex(
            model_name='healthprogrammeitem',
            index=models.Index(fields=['executive_profile', 'order'], name='executive_h_executi_1689bd_idx'),
        ),
        migrations.AddIndex(
            model_name='healthscoresnapshot',
            index=models.Index(fields=['executive_profile', '-recorded_at'], name='executive_h_executi_c60faf_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['executive_profile', 'category', '-recorded_at'], name='executive_l_executi_2ccff3_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['executive_profile', 'active'], name='executive_m_executi_fd8ab4_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicationalert',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved', False), ('resolved_at__isnull', True)), models.Q(('resolved', True), ('resolved_at__isnull', False)), _connector='OR'), name='med_alert_resolved_consistency'),
        ),
        migrations.AddIndex(
            model_name='medicationschedule',
            index=models.Index(fields=['medication', 'scheduled_for'], name='executive_m_medicat_9fa1b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicationschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'taken'), ('taken_at__isnull', False)), models.Q(('status', 'taken'), _negated=True), _connector='OR'), name='med_schedule_taken_requires_timestamp'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['executive_profile', 'metric', '-recorded_at'], name='executive_r_executi_bb436a_idx'),
        ),
        migrations.AddConstraint(
            model_name='weeklyreport',
            constraint=models.UniqueConstraint(fields=('executive_profile', 'period', 'period_start'), name='weekly_report_unique_period_start'),
        ),
        migrations.AddConstraint(
            model_name='weeklyreport',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='weekly_report_period_end_after_start'),
        ),
    ]
