# Generated by Django 5.2.12 on 2026-09-25 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executive_profile', to=settings.AUTH_USER_MODEL)),
                ('user_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executive_profile', to='services.userservice')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['created_by'], name='executive_e_created_b437e4_idx')],
            },
        ),
    ]
