# Generated by Django 5.2.12 on 2026-09-25 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='executiveprofile',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('twice', 'Twice'), ('managed', 'Managed')], default='managed', max_length=20),
        ),
        migrations.AddField(
            model_name='executiveprofile',
            name='monitoring',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='executiveprofile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_executive_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='executiveprofile',
            name='user_service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='executive_profiles', to='services.userservice'),
        ),
    ]
