# Generated by Django 5.2.12 on 2026-09-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0002_executiveprofile_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Health Manager'), ('physician', 'Physician'), ('nurse', 'Nurse')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_team', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['role', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('flag', 'Flag')], default='info', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(blank=True, max_length=255)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='UpcomingCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('scheduled_for', models.DateTimeField()),
                ('provided_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_care', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('bp', 'Blood Pressure'), ('heartRate', 'Heart Rate'), ('oxygen', 'Oxygen'), ('weight', 'Weight'), ('glucose', 'Glucose')], max_length=20)),
                ('value', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('elevated', 'Elevated'), ('high', 'High'), ('low', 'Low'), ('watch', 'Watch')], default='normal', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['executive_profile', 'metric'], name='executive_r_executi_d6641b_idx')],
            },
        ),
    ]
