# Generated by Django 5.2.12 on 2026-09-26 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0003_careteammember_healthalert_healthscoresnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('eta_minutes', models.PositiveSmallIntegerField(default=15)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_events', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyTimelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('current', 'Current'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('happened_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='executive.emergencyevent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HealthProgrammeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('on', 'On'), ('soon', 'Soon'), ('booked', 'Booked'), ('track', 'On Track'), ('scheduled', 'Scheduled')], default='scheduled', max_length=20)),
                ('icon_key', models.CharField(blank=True, max_length=32)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('next_due', models.DateTimeField(blank=True, null=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_items', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=64)),
                ('tone', models.CharField(choices=[('normal', 'Normal'), ('elevated', 'Elevated'), ('high', 'High'), ('low', 'Low'), ('watch', 'Watch')], default='normal', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('purpose', models.CharField(blank=True, max_length=150)),
                ('dosage', models.CharField(blank=True, max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('high', 'High'), ('reminder', 'Reminder')], default='reminder', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_alerts', to='executive.executiveprofile')),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='executive.medication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_label', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('taken', 'Taken'), ('due', 'Due'), ('upcoming', 'Upcoming'), ('missed', 'Missed')], default='upcoming', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='executive.medication')),
            ],
            options={
                'ordering': ['scheduled_for', 'time_label'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('week', 'Week'), ('month', 'Month')], default='week', max_length=10)),
                ('label', models.CharField(max_length=80)),
                ('range_label', models.CharField(max_length=80)),
                ('physician_name', models.CharField(blank=True, max_length=150)),
                ('nurse_name', models.CharField(blank=True, max_length=150)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('status_title', models.CharField(blank=True, max_length=120)),
                ('status_summary', models.TextField(blank=True)),
                ('vitals', models.JSONField(blank=True, default=list)),
                ('trends', models.JSONField(blank=True, default=list)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('next_steps', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('executive_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='executive.executiveprofile')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emergencyevent',
            index=models.Index(fields=['executive_profile', 'status'], name='executive_e_executi_52bde6_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['executive_profile', 'category'], name='executive_l_executi_18717c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('executive_profile', 'period', 'range_label')},
        ),
    ]
