# Generated by Django 5.2.12 on 2026-10-02 22:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0004_emergencyevent_emergencytimelinestep_and_more'),
        ('services', '0003_alter_userservice_onboarded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationschedule',
            options={'ordering': ['scheduled_for']},
        ),
        migrations.RemoveIndex(
            model_name='executiveprofile',
            name='executive_e_created_b437e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='labresult',
            name='executive_l_executi_18717c_idx',
        ),
        migrations.RemoveIndex(
            model_name='reading',
            name='executive_r_executi_d6641b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='medicationschedule',
            name='time_label',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='value',
        ),
        migrations.AddField(
            model_name='careteammember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='executiveprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='healthalert',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='healthalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='healthprogrammeitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthprogrammeitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='unit',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='labresult',
            name='value_numeric',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medicationalert',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='display_value',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='reading',
            name='unit',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='reading',
            name='value_numeric',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='value_secondary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='e.g. diastolic when metric=bp', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='upcomingcare',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='period_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='period_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='careteammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='careteammember',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='emergencyevent',
            name='activated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emergencytimelinestep',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='executiveprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='executiveprofile',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('twice', 'Twice Weekly'), ('managed', 'Managed')], default='managed', max_length=20),
        ),
        migrations.AlterField(
            model_name='executiveprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='executiveprofile',
            name='user_service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='executive_profile', to='services.userservice'),
        ),
        migrations.AlterField(
            model_name='healthalert',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='healthalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='healthalert',
            name='resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='healthscoresnapshot',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='healthscoresnapshot',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medication',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='medicationalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='medicationalert',
            name='resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='scheduled_for',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='metric',
            field=models.CharField(choices=[('bp', 'Blood Pressure'), ('heartRate', 'Heart Rate'), ('oxygen', 'Oxygen'), ('weight', 'Weight'), ('glucose', 'Glucose'), ('general', 'General')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reading',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='upcomingcare',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='upcomingcare',
            name='scheduled_for',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='careteammember',
            index=models.Index(fields=['executive_profile', 'role'], name='executive_c_executi_1399db_idx'),
        ),
        migrations.AddIndex(
            model_name='executiveprofile',
            index=models.Index(fields=['deleted_at'], name='executive_e_deleted_18428f_idx'),
        ),
        migrations.AddIndex(
            model_name='healthalert',
            index=models.Index(fields=['executive_profile', 'resolved'], name='executive_h_executi_5c1ece_idx'),
        ),
        migrations.AddIndex(
            model_name='healthprogrammeitem',
            index=models.Index(fields=['executive_profile', 'order'], name='executive_h_executi_1689bd_idx'),
        ),
        migrations.AddIndex(
            model_name='healthscoresnapshot',
            index=models.Index(fields=['executive_profile', '-recorded_at'], name='executive_h_executi_c60faf_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['executive_profile', 'category', '-recorded_at'], name='executive_l_executi_2ccff3_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['executive_profile', 'active'], name='executive_m_executi_fd8ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationschedule',
            index=models.Index(fields=['medication', 'scheduled_for'], name='executive_m_medicat_9fa1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['executive_profile', 'metric', '-recorded_at'], name='executive_r_executi_bb436a_idx'),
        ),
        migrations.AddConstraint(
            model_name='emergencyevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', False), ('status', 'resolved')), models.Q(('status', 'resolved'), _negated=True), _connector='OR'), name='emergency_resolved_requires_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='emergencytimelinestep',
            constraint=models.UniqueConstraint(fields=('event', 'order'), name='emergency_step_unique_order_per_event'),
        ),
        migrations.AddConstraint(
            model_name='executiveprofile',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_at__isnull', True), ('deleted_at__isnull', False), _connector='OR'), name='exec_profile_deleted_flag'),
        ),
        migrations.AddConstraint(
            model_name='healthalert',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved', False), ('resolved_at__isnull', True)), models.Q(('resolved', True), ('resolved_at__isnull', False)), _connector='OR'), name='health_alert_resolved_consistency'),
        ),
        migrations.AddConstraint(
            model_name='medicationalert',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved', False), ('resolved_at__isnull', True)), models.Q(('resolved', True), ('resolved_at__isnull', False)), _connector='OR'), name='med_alert_resolved_consistency'),
        ),
        migrations.AddConstraint(
            model_name='medicationschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'taken'), ('taken_at__isnull', False)), models.Q(('status', 'taken'), _negated=True), _connector='OR'), name='med_schedule_taken_requires_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='weeklyreport',
            constraint=models.UniqueConstraint(fields=('executive_profile', 'period', 'period_start'), name='weekly_report_unique_period_start'),
        ),
        migrations.AddConstraint(
            model_name='weeklyreport',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='weekly_report_period_end_after_start'),
        ),
    ]
